### ISSUE TITLE
Installer is missing

### ISSUE THREAD

**Issue by darkoverlordofdata** [spences10/VBA-IDE-Code-Export#81]
I am trying to follow the instructions from the readme, but fail at step 1;

	1. [Download](https://github.com/spences10/VBA-IDE-Code-Export/releases) the
	   add-in installer (e.g. `CodeExport_setup_1.2.3.exe`)

There is no *.exe by any name in the release area or the archives therein.

**Comment by mattpalermo** [comment]
Damn you're right. I must have forgot to upload the compiled files last release! You'll have to either compile from the source code or ask @spences10 nicely to upload some files :)

**Comment by spences10** [comment]
Say whaaaaaat!?

![giphy](https://cloud.githubusercontent.com/assets/234708/26814403/4baa7c64-4a7d-11e7-82d8-28deeba003c0.gif)

@mattpalermo do you have a `*.exe` kicking around? Otherwise I'll take this out and just stick with having a pre compiled `.xlam`

@darkoverlordofdata I think you'd be best off, lilke @mattpalermo says to compile from source if you're in a hurry 👍

**Comment by darkoverlordofdata** [comment]
I downloaded the *.xlam from release and followed the instructions to build an exe. That works. Thanks.

**Comment by mattpalermo** [comment]
@spences10 perhaps you will need to go back to the `xlam` if that is what you are comfortable with.

**Comment by spences10** [comment]
Hey @mattpalermo, hows things buddy?

Lost a load of momentum with this recently, time to pick things up again!! 

Trying to recall the reasoning behind having an installer now over just using the BLOB?
